spring.application.name=bhakti-hub
spring.datasource.url=jdbc:mysql://localhost:3306/bhakti_hub
spring.datasource.username=root
spring.datasource.password=prachi

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080